server:
  port: 8090
spring:
  kafka:
    bootstrap-servers: 10.103.22.93:9093,10.103.22.92:9093,10.103.22.89:9093
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-20191209

